#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Store incoming environment and initialise
#======================================================================================================================

nu -c "use bf env ; env store" > /dev/null
nu -c "use bf-php init ; init"


#======================================================================================================================
# Execute PHP
# See https://github.com/docker-library/php/blob/master/8.3/alpine3.20/cli/docker-php-entrypoint
#======================================================================================================================

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php "$@"
fi

# enter workspace directory and execute PHP
cd /ws
exec "$@"
